# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_R=3.3.2
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "W6/uoGfLj3HXewLeQuCLfqcSfP+55MwRenwLZ3fVSs9MFYB2oD8o19MPpZawVlDOKYfIcE7clXPsroTjHMlTCGylq37aFED6cUTMKNlSoHg9UOCnurch7hQaK4e9BEa56Xbhwtjzh/Bw4jwLhBegpLRWaAlCyJX/t8qUXJDHwiis/yg6os+uu6UPI0BRgVYCL1s5IuHWu7Yt6pDaPhkxSWkF9aotYfFpIEhYIpCXgwBmXxHBtDKz/YjdgTGv2p0FUGmdOz/DOtsjSl5CsC4XrYRFE8oB7zkTdUjRnWzxV2YMFiWuK21mV53nhhbuaolXqX1g2m8OIeY0qbwvhnG1j6NzXu8OcamAewrye+LBQtXPtku0h4vyiFXC5L1ykno7grex/6VWBAf5JeDPBw7utW0IeCB3fqlwaqqc0LJGqevcPQOZz/PDIMfYe6PNuVgzmrgX5irWI2M1V4aNahd0LoRRt6ZGArCQwkAxYpgZTRphGvc7HCUAqyzpfDQFw9JEbLr99pq+SeZwCznb6OiMw2mf2rqvd8sVBACZnHa5f2we9Pn+ZoBDQ4S2dKXb1AdPTj6lx1nRyRC8Y8cwZDSIz0lXStTJlhHjt+lOZZKZ4ZLcln6ZKiRruZM93/XxCZsbAIKQ8yP4pwBHinnK9q/wxFLzsIA1A9/XgnFIc/cbnAI="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
