travis:
  secure:
    BINSTAR_TOKEN: KDiCL0U2/lGS3PCzS84Bm3ZpcoCEE0sygaX52sSDCLd1PcYE9guQ1w1enp6jDfFTalbJFKJ2VF8htIdf5eGgP2eRTgtYzSgWaeBDA37jkV7dOjzOClanQxFwHoBxWPfuNMptEj5E83N2rayoU+udOMHvl/VywrqrGp/5XA6pGex04lQGhU0A1B0TfYMUtUejSSATjzameFsmOWnm+mPMBJhcJdTcG+AO79FJXdKzZcE1PbPodrvHLVi/eA9qpop78QzlFcE7m9ggMGcjgaKQE9BnurIj08Ns72O5D75AKzuYnkZScJT9G/b/u5oqP+9v7nhdWsSh4tFJhUauahLdXFfNNMob+myvn5BJqoCG1z3y9k4aQknlsSVGkgHegNWnWvydv+j5Qwj74lqMoWwLg9ISB2Gmq1O+45FmlNS61y7aj5nS4WM81oQNrnTerxRBBeB7Jb0XUWWdaYik4PRvEgapFzYA349Mk8WPPBqzAPlpeh+9F80dGMso3PPOTCfQoATr8UcpWGHoooS1nOtk9s71mubZvyVaO6tEgY8ox5Gf4FdIyib4+/vL2k+lT1ag32nZN6Nj/cV1OSNRfQZ68T8It6iRpCAnKQPX/xguf0ZmjneHloOpVQgkEHog7D48zQhbtO/7PYfXyrs/OubszVB4bwzz2dWX7lUBVb5gE4k=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
