travis:
  secure:
    BINSTAR_TOKEN: l2Oa39ATvln/hcoj0d7iq3jN6j2SDAjPrqp4baKjBQX+W3VVrLUfWWRTp0eVlKhH6qHiNjdBNZOFxYDFTNbTO8jwbsotC+WvZlmvkv+2HLr7kIjYeTe6SOpQsx+7mXknU38Ob7CuvZxGjefo7pNOA5QltAkarlyGGnoam5XaSNCbdgW3TfnQEMaz46ygVQvTkz+nQASrnKBols/kd3s6yBMvkeBzYN2iTUd/cy2UTIN7WGs+wNXP84YqMyZb+Ws8hN/s+XSjN4BHlG7fi3eYw2qzCIT81juuL4Gz0LqLnZQjc1VhGTsptyasBk0jk3aH63LnmSvuivzDnKdnLsurOV7/VWlA15t3jwUtdnYMzAqB/WJeYhL0Fnx3UHeQRjhifS3jgB0oo1bVNdq7Yl2Yd9Qb/ENjMwshx8iRMdlE1NVyvgj5jdEXldJWeRrTDWK3tvM60s/5xfGhfCSiAXZ7ikELc99ZlXwgd/o2mBmXq4JubOdfWvsWUhwW4Yd6shtQtgq8Xcs1S09848xOj8IMSwv8HkdhhlsFUPNu3M8jrrcfG7nGN2ncQimiu+8tzFouxAA/Y+mmWQdI+jxd9aPc5JHKscQbck2deur4IFwmQySlsQ/hhpY+Z3D05K9m3hvTweUKzIc+4RezjT9bJ5zEovz+4DwzcLNrOJX/02BKAC0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
