travis:
  secure:
    BINSTAR_TOKEN: g/O+1h1uMMcaPD1fkX7+g6dwXMGTpEbVQVyYrq1NJLvQFLfKknzgSU8EzIP8lcrJAcd3aGrGl6qnUvtiIjO9Y2nma51kuoV9ZpIE0CE6FujiqLxV+dfadJjQOZAo9WJArpyaNzMttAtag2TEDbLtURPJgTdPi8T54doqHhrOYYIWp1j6sFoIS6pPto89KSsE/reWoaOoB1M2fkcZbNwnvgLClmzUK5jEz0nSE9aiLwCvWR5R1vR/IvLl/yOMGJxxn8upRKA/lAO8yOBcD/gEQzsAqBkkIlt489WCEUVAJxItB6gSBESLpp8jcEchpcPDq8IfyGywk/Q3nZlkv21F/JUJ+lvqDOMXRkjj9T+077H0M6FBTrGk52g7w0FqswbdhMyCwTQaPNrrSEFONVF1IGwoT0dqKA1D+mMXP/Wrx4PV8eHHrxvlPxJNfLOKmWflrN1BzwrcCeEdgTXODsQE9Ezg8VUm+j3Grs/oDXM6LOPMTA4bQONbIimdQM80kBV6zsCxyYyaF7y3IAPwdB+hmo8AexJJNXuhILfMynpWjqswn4tGHafijc/ejfES4kdWYcjsm8ICqauApue3i1OWpGdz/X8er75TfeHxnvS09k0LbdvOFLfX3XofBlm4Bq8TQWS80A8iWAJmQSVGLVjDkHoScDIVlznmzTIoX2Aq1ig=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
