travis:
  secure:
    BINSTAR_TOKEN: cnOpkBBCZwKNOPORdUw25WlFtlSwv94bpfJGHMDYcrSVJhzWR01wI+KqBh1vz+hYhyol/6XkmaYSBQg59sqLeG2DAhdaAsFQXNhfjo/ku10HJncSQFNGS5VvRWPKDw0mx14SSjA+eyfGg0JBjwr4BFWv7T3rVvI2W2SvZZ3canfr51qN5OGqEKVPXYPypDSAWVUwtXNfsLrSo3KWAlU8YaNl1z2u6HJTNvWisW+2gjrliSLvLzSowsKwbfxiwno6Xbof7Xz5ZbMAsnj7rg4apz1wgAQG5uF0ImI2p/v70Px5ihxrY7akQGzT8C9q55rAZzj3kIDeOgfjUq7ScrEMyYTjH9pb1DH4J79x9Qb33/qquJ7o22FjOOVoaHRaiDPIZJsO84ocucug/W5mor+7E+wGmCzfxhajKkR1nBMvn5etNXFPEHObNJYYsVcG+rlv3O0Tqfef4Ve5ePWEgm0zNs3U/yl1fikbj9UpqzZZsmyQM6H8BB0CCzGO2a29ES/xng0z7wXT565j7cPmiZpGtK1pPfppIcBXBJpu35/mFG5Sg32uqTZM8gyRLlDYBlFPUILK53/d69PCp8H7eK9wy5QWaTUPCWNFVL2C9b6amnsNYNL7Ooj0f+YjGXvKD1HEHTR6m51zXBYnkQtsHvdWB1SMOlYXjnuhtVt0kzMZU7U=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
