travis:
  secure:
    BINSTAR_TOKEN: W6/uoGfLj3HXewLeQuCLfqcSfP+55MwRenwLZ3fVSs9MFYB2oD8o19MPpZawVlDOKYfIcE7clXPsroTjHMlTCGylq37aFED6cUTMKNlSoHg9UOCnurch7hQaK4e9BEa56Xbhwtjzh/Bw4jwLhBegpLRWaAlCyJX/t8qUXJDHwiis/yg6os+uu6UPI0BRgVYCL1s5IuHWu7Yt6pDaPhkxSWkF9aotYfFpIEhYIpCXgwBmXxHBtDKz/YjdgTGv2p0FUGmdOz/DOtsjSl5CsC4XrYRFE8oB7zkTdUjRnWzxV2YMFiWuK21mV53nhhbuaolXqX1g2m8OIeY0qbwvhnG1j6NzXu8OcamAewrye+LBQtXPtku0h4vyiFXC5L1ykno7grex/6VWBAf5JeDPBw7utW0IeCB3fqlwaqqc0LJGqevcPQOZz/PDIMfYe6PNuVgzmrgX5irWI2M1V4aNahd0LoRRt6ZGArCQwkAxYpgZTRphGvc7HCUAqyzpfDQFw9JEbLr99pq+SeZwCznb6OiMw2mf2rqvd8sVBACZnHa5f2we9Pn+ZoBDQ4S2dKXb1AdPTj6lx1nRyRC8Y8cwZDSIz0lXStTJlhHjt+lOZZKZ4ZLcln6ZKiRruZM93/XxCZsbAIKQ8yP4pwBHinnK9q/wxFLzsIA1A9/XgnFIc/cbnAI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
