travis:
  secure:
    BINSTAR_TOKEN: Uzx6aiYysikEX/Klxz8GV8tb240ByFW2QCzz0P+rCvYuRIV9/IxNg88bvtH/xJXNqf2LEtHM/sEaMM9CXrPW3Cioi6TR7DpvRsJajDDG6UiwCBAHPlGIvRkb40xYzjslOvPZMRA/+7oWYn3KXAQlu0CxuS7H/tEI5JijGjQ1papx3ODO9TJoMdfPvszbuHgMfMI229nN+pIy66PlZ9W5T/Pfz2EFHTFp9PyUKnvLH6yTViS+fpMcNsShEGhHkLdteDtapW7QcjDiKRp6GFbBZyroNToPK5hUd3PrNqFVonB8Ez++yA0So8YAO8nZKblU9RbAyF5Y1A1F3lREb8jkHWMdoy9vTvlrtzhMajby3FONjybVA6VsCCUHBNjDU2WyuHVKTO+TEI2y+mucp3NAJRor7nDw+1X/rZPHoTh8AVy/JDBNkb5Tpue3aT6ILfsgyonnXKKchKh58/5nzUHmNUTHkDSmVatHI6Y2UirsRpCK5uN/zOg0myfNUYLQ/YbouQRQ8t7TZKIOUNCbNrG+jXOPKmAmyjgiGX9YT0I3MkxtMhMW4Hwp9B93ZFOjitj0MzokU8M1mnAeNPVMiQ1f97Z1BpYWrV2xR62wEBSMkhYGM1rDNQ84ctE3MX0NYuH2hH8gSc6DebNN6MaROsHpRNuJTS8JVBAy5FdIpA2WBgg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
