travis:
  secure:
    BINSTAR_TOKEN: Xt9dLmsYQil94xAt6GcYJ3B4LEVRIEm2pPju7bHg5hI7C8XWrFEoNmj9K1CGP2+q+hhPjRI/ohBRaRibd1YBmu2pK0h5wXXBoGHGgeXFvnI3gEpQme54/yrv1bQhAOzQFS6Ax67iRn7aiw+/e9Je4ycSXtBjALa3HhLQ8vBRk1RFTkQto7keyl91elxtBbXOJJ2Fm3dP8oNkZNR8iqW4AGan804e1Nai/RvLJqRHwiMWChIsHRWwB4FYccUecmBKY0zFv25jYgbaxRrDtT5vCKb5GZ+uUDYBwH3n3O6H2gBVlgxZDobUPX7EaNFgUxQuLvfMGLdqhVINL+xQRTsRy6v7SBCgQxM2myL5+UnQlo4hiOOiWjMKwoO66Q1+eLE9/EuSxZoUR23fd5WNnqPOUgfLEwFFhkpr8OhwKETU24tRct0Hlxs/A8v1YhacGoZ0JsRGVtPcpt/JZhS0mfJYqUwzNbiDAkyS5MxMDZqkBxZwuAPcZsJvmuI2n08ODmFv/CtVp81OKZk7f/kjN2aCIdGwvgY4tS4HsQs2AmnoBaoxPAIwSaqS2c4jEzfsELe2zSY8WFDMLxzzB4wCK/7lPSmEb44qwFTczFA/Dvff7lPhU9xOzcxZBzKZo+br/F3wE0yGjKiTczIDUetbWeC7or2T6EzE5V9l39fDFTWcqT8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
