travis:
  secure:
    BINSTAR_TOKEN: lJepgjqbwGHJHUbNylXIIkou3utvSYncn+ny0DTTBpFNPtELrILTIU2SUUS7Xong4ALTEZIYT3HQfC40BOipqe8pgQD60n6FIFzbb5XIqezVuJRGjlBrp9qqdHR18P98M7sZ0dpAlvQ/eT4WABJoZf/8Uvd7GXRJG88inInzXhWiPPxWo5ueC66BnYXpwEZzL5QGnmFXwA28+rXJ6j04DmVsS1CcVBgs1LefGWs2x0kXjn20mx09AK8WtAAQy77jnCbW4cA1OqkhSffDIr0RnIcRGeqb4W/ijRTVFleyCfXhFa/hhkxSsfGbExa7aMI85fD/8iw/AcKatgNvwrYrrOyUrNyXegx3dnMBQq1jrP2j16tOLfVmSBu4rtG1scrP8P4cfiQoGp6W8sHzKFHDbQ8yZZmuFNuL2I6jaiIx2yEdORSoM2QH3DsmR9MMKrt3tWfv4/2L3XW3+lwKD9Ioh4RVwRn+po/AaGT/LCfCH4Pjrsr/C9e9xGp2NVMF4+777js4YVm4zCmW5Mh9z81PhHOwcTL0JiS7+AOZJH2b2/f8mctTXwoucMvU+SXaMLs1VgGX6SjjEl5giQFC6rJ7wo2fjI3F1GgiFj5+e9XJIhGvIugznIDdJ50ygO2OH/Do2FlUDkFXCvsxPQoUTnab2S2qXTwrexiU5E30Ai8YCI0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
