travis:
  secure:
    BINSTAR_TOKEN: I71Sbd+JvGrSS6bskaXn2Oi3cLonh8BWssWD1/Tn9J3sc8V1BljT2S1QI2f4A0WRD7nGCCIj75Gxttw3eBg4Dm5AU+mQnS69fz4vUJi42pgI5s4gBM+AByRjR8QZwt1zQIEfKTr/GU0hAY9nLk5dgxsPLyArHDkvVF8Hf/9GJRdFu5iFkxLANemB73v4csLGEEdmNYDdFmuzw8LJLb5aCMjd+grB+5pbHntyTrJs4zOhNPBKZ1LSFwLJAYJ4kQI5acPNhyZkv1wk1BvnmE4LAgxmV0oFPl8NtTU/UGOXSi4wNGkpC5JvgKSHcof2/3LkELqDg/gENmAJsKj2Qc0cFH2Fj90Q1fi4U92pGtLpEggbPMMnG8BTS+nVpz05ADM3QO5Ga3i2iwu7b4gHe1QLk6wtzoqtbHLMPy5+i5AroWHWkTS0pSItkLE2FvW692wD5qFwWOEA4dDWIfAvcDXc/B/JWNBytHQ2olU+EqUxkp998N1jZ7f3IumD23EKQyFpmvu1NNT+V0/0doW66bMitQDqP0cIOMSDu3x8kqTLl8HKkhZ3ydkniNSMwM3oYPWnOl9W+FdTYl/PTygDPz8XfYGGlEVs4BUszHbLTr3Odta0GURUZywpAE3vR4o4gbi/OhAp4jOb0cg1ssI+sMJBJuXAb0NT0wBIKm+OT8P8ViE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
